version: '2.4'
services:
  frontend:
    build:
      context: ./front-end
    ports:
      - "5173:5173"  # Adjust the ports as needed
    depends_on:
      - backend  # This ensures that the backend service starts before the frontend service

  backend:
    build:
      context: ./back-end
    ports:
      - "3000:3000"  # Adjust the ports as needed
